/**
 * This file is automatically generated, use caution when editing it by hand.
 */

import { BadgeStyles } from './Badge'
import { ButtonStyles } from './Button'
import { FlexStyles } from './Flex'
import { PaperStyles } from './Paper'
import { TextStyles } from './Text'
import { GlassStyles } from './Glass'
import { CardStyles } from './Card'
import {
  MenuItemStyles,
  MenuListPanelStyles,
  MenuListSheetStyles,
  MenuStyles,
} from './Menu'
import {
  CheckboxStyles,
  FieldErrorStyles,
  FieldLabelStyles,
  FieldLabelRequiredStyles,
  FormErrorStyles,
  InputStyles,
  SelectButtonStyles,
  SelectListStyles,
} from './forms'
import { DividerStyles } from './Divider'
import { OverlayStyles } from './Overlay'
import { ModalStyles } from './Modal'
import { DialogStyles } from './Dialog'
import { BreadcrumbsStyles } from './Breadcrumbs'
import { LinkStyles } from './Link'
import {
  PaginationButtonStyles,
  PaginationContainerStyles,
  PaginationListStyles,
} from './Pagination'
// import anchor

export const AtomicStyles = {
  Modal: ModalStyles,
  Overlay: OverlayStyles,
  SelectButton: SelectButtonStyles,
  SelectList: SelectListStyles,
  Divider: DividerStyles,
  Menu: MenuStyles,
  MenuListPanel: MenuListPanelStyles,
  MenuListSheet: MenuListSheetStyles,
  MenuItem: MenuItemStyles,
  Checkbox: CheckboxStyles,
  FieldError: FieldErrorStyles,
  FieldLabel: FieldLabelStyles,
  FieldLabelRequired: FieldLabelRequiredStyles,
  FormError: FormErrorStyles,
  Card: CardStyles,
  Glass: GlassStyles,
  Text: TextStyles,
  Paper: PaperStyles,
  Flex: FlexStyles,
  Input: InputStyles,
  Badge: BadgeStyles,
  Button: ButtonStyles,
  Dialog: DialogStyles,
  Breadcrumbs: BreadcrumbsStyles,
  Link: LinkStyles,
  PaginationButton: PaginationButtonStyles,
  PaginationContainer: PaginationContainerStyles,
  PaginationList: PaginationListStyles,
  // export anchor
}
